baseURL = "https://tomr.au"
languageCode = "en-au"
title = "Thomas Rückstieß"
copyright = "Thomas Rückstieß ©"

[params]
  name = "Thomas Rückstieß"
  description = "Something about me goes here."
  initials = "TR"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/tomonezero"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/rueckstiess"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/rueckstiess/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1

#  [[menu.main]]
#    name = "Projects"
#    url = "/projects/"
#    weight = 2
#  [[menu.main]]
#    name = "Library"
#    url = "/library/"
#    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'igor'

  